apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: lofar-stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lofar-stage
  template:
    metadata:
      labels:
        app: lofar-stage
    spec:
      containers:
        - name: lofar-stage
          image: microinfrastructure/adaptor-lofar-stage
          env:
            - name: "DEBUG"
              value: "true"
            - name: "AMQP_HOST"
              value: ""
---
apiVersion: v1
kind: Service
metadata:
  name: lofar-stage
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 5000
  externalIPs:
    - "145.100.130.145"
  selector:
    app: lofar-stage